### PR TITLE
Fix some deprecation warnings

### PR DESCRIPTION
**Pull request by timholy**
Note this is against teh/constrained

### CODE REVIEW

**Comment by pkofod** [comment]
Sorry, we cannot merge more PRs regarding teh/constrained before #303 is completed.

(just kiddinng ofc, though I actually started the process of bringing that up to date just yesterday!)

**Comment by pkofod** [comment]
Are you ok with the v0.5 failures? Then maybe you should update the travis file. Not that anyone but you and your lab would really care, but... Then you get to see the green check mark!

**Comment by timholy** [comment]
> (just kiddinng ofc, though I actually started the process of bringing that up to date just yesterday!)

That's great to hear! Do keep in mind that because #303 won't actually be useful to my lab (at least, not for our "main" need) and I already maintain far too many other packages, it's pretty much up to others to keep it working and fix bugs. If you have questions about how it works I can hopefully help answer them.

**Comment by pkofod** [comment]
Do you want me to merge it?

**Comment by timholy** [comment]
Yes please. (I don't have permission.)

**Comment by pkofod** [comment]
Must have happened in the org move. I’ll have a look at it later

**Pull request merged**
