### PR TITLE
Move initial condition inside box

### PR DESCRIPTION
**Pull request by anriseth**
I prefer to warn the user and move their initial guess inside the box, rather than error and exit.

The updated values are rather arbitrary.

### CODE REVIEW

**Comment by pkofod** [comment]
Any chance you could just mention it briefly? It is a behavior chance after all. But other than that, fine by me.

**Comment by anriseth** [comment]
Do you mean mention in NEWS?

**Comment by pkofod** [comment]
That's what I mean, I missed a few words there :)

**Comment by KristofferC** [comment]
FWIW I disagree with this. If the user provides obviously faulty data then a function should just error out quickly and not guess what was intended. It is just as likely that the bounds where entered incorrectly as the initial condition.

**Comment by anriseth** [comment]
Okay. How about when `x[i] == l[i]` or `x[i] == u[i]`, that is when the
user sets the initial guess to be *on* the boundary?
This happens to me quite often when I call Fminbox as a small part of a
bigger simulation, and is the main problem I wanted to fix with this PR.

**Comment by KristofferC** [comment]
That sounds like a good idea.

**Comment by pkofod** [comment]
New version is :+1:

There's a `@test_warn` macro on v0.6 at least, that lets you test for an exact string, or if a regex matches the warning message.

**Comment by anriseth** [comment]
This is ready to merge. Newton trust region is killing Travis on Julia 0.5, but the tests on constrained optimisation passed:)

**Comment by pkofod** [comment]
In a sense this is still correcting behavior that could indicate that the user did someething wrong, and didn't intend for the code to be run with wrong starting values. However, I do appreciate that to many users, "on the boundary" seems like a legal place to start, it is just that our barrier function does not like it. Unless someone disagrees, we can go ahead and merge this.

**Comment by anriseth** [comment]
> In a sense this is still correcting behavior that could indicate that the user did someething wrong, and didn't intend for the code to be run with wrong starting values. However, I do appreciate that to many users, "on the boundary" seems like a legal place to start, it is just that our barrier function does not like it.

Let's hope the warning is big enough for them to realise that they've done something bad

**Pull request merged**
