### PR TITLE
add info on if time_limit reached

### PR DESCRIPTION
**Pull request by magerton**
partial fix for #739

### CODE REVIEW

**Comment by pkofod** [comment]
> partial fix for

How should I understand this phrasing. Do you intend to fix the methods that are not yet fixed as well?

**Comment by magerton** [comment]
Hi @pkofod , I'm afraid I don't have the time right now to fix the other methods that I'm not familiar with. I hope that's okay.

**Comment by magerton** [comment]
@pkofod , just to clarify — the fix is implemented for the unconstrained multivariate case, but not the constrained solvers. I added a wrapper for `MultivariateOptimizationResults` so that the constrained tests pass.

**Comment by pkofod** [comment]
> Hi @pkofod , I'm afraid I don't have the time right now to fix the other methods that I'm not familiar with. I hope that's okay.

That's fine, I appreciate the effort so far! I'll leave this open for now. I might have some time later to fix it for constrained and univariate, and then we can move forward.

**Comment by pkofod** [comment]
Havn't forgotten, I'll get around to this asap. Thanks for being patient

**Comment by magerton** [comment]
> 
> 
> Havn't forgotten, I'll get around to this asap. Thanks for being patient

Thanks, @pkofod , and no worries! I appreciate your attention to the issue!

**Comment by pkofod** [comment]
Thanks, I'll fix the other ones.

**Pull request merged**
