### PR TITLE
relax type constraints to support Measurements

### LINKED ISSUE #823: how to make optim work with Measuements
Hi:
I want to use some Measurements variable in optim problem.
but have some error,how do I handle it,wish to get reply

using Measurements,Optim
f(x)=(1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
x=zeros(Measurement{Float64},2)
optimize(f,x)

### PR DESCRIPTION
**Pull request by longemen3000**
paves the way to use Optim with Measurements. calculations runs and seems to propagate the uncertainty. fixes #823 . fixing the show problem could be done in two ways:
- trying to use other way of formatting numbers, compatible with `Measurements`.
- displaying only the value. this can be done on a two liner:
```
using Printf,Measurements
Printf.tofloat(x::Measurement) = Printf.tofloat(Measurements.value(x))
```
if the user doesnt want to do this, they can directly use Optim.minimizer(res) or Optim.minimum(res) and not show the summary of the optimization procedure.
as this type relaxation doesnt seem to affect other number types, this is an strict improvement over the current situation.

### CODE REVIEW

**Comment by longemen3000** [comment]
on my local machine, only tests with Momentum Gradient Descent seem to fail,seems unrelated

**Comment by longemen3000** [comment]
@pkofod can you check this PR? The printing mechanism on measurements has been already fixed

**Comment by pkofod** [comment]
> on my local machine, only tests with Momentum Gradient Descent seem to fail,seems unrelated

Momentum gradient descent is very unstable. Last unit differences can cause it to explode. I'll have a look at the PR :)

**Comment by pkofod** [comment]
@longemen3000 can you add a test?

**Comment by longemen3000** [comment]
something like the example problem in #823 ?

**Comment by longemen3000** [comment]
i added the #823 example problem, work well but im testing. after that i commit

**Comment by longemen3000** [comment]
@pkofod can you check on this? It seems that the new github policy is blocking the test from running

**Comment by pkofod** [comment]
Yes, but unfortunately the "approve and run" button leads me to a error 500 page ..

**Comment by longemen3000** [comment]
The error in the tests is unrelated (convergence on particle swarm)

**Comment by pkofod** [comment]
> The error in the tests is unrelated (convergence on particle swarm)

Yes that's just because I have to use StableRNGs for the tests. Thanks for the contribution once again :)

**Comment by Boxylmer** [comment]
> paves the way to use Optim with Measurements. calculations runs **and seems to propagate the uncertainty.** 

Has anyone verified the resulting uncertainty is correctly propagated?

**Pull request merged**
