### PR TITLE
Use alphaguess functionality from LineSearches

### LINKED ISSUE #294: StepLength Extrapolation
Aside from 
- search direction 
- line search
  the step-length extrapolation (from step-length, gradient and function history) is maybe the most crucial aspect of the optimisation algorithms implemented in Optim. 

I suggest to (minimally) refactor `Optim` to allow the user to choose how to perform this? E.g. `cg.jl` uses `alphatry` which is HZ's method, `LBFGS` uses just the previous step. But I'd really like to play around or even try my own variants.

CC: @pkofod @anriseth 
   (this should probably be done in parallel in `Optim` and `LineSearches`)

### PR DESCRIPTION
**Pull request by anriseth**
Lets the user decide the initial step length. 
- Fixes #294 
- Needs https://github.com/JuliaNLSolvers/LineSearches.jl/pull/70

TODO: 
- [x] Documentation

This also makes some changes to default behaviour. I think we should do a quick benchmark to check whether they make things worse or not. **UPDATE: I'll leave the defaults untouched. We need a better benchmarking functionality to decide on default changes**
- [x] ConjugateGradient initial step length guess in the first iteration uses HZ#I0, instead of HZ#I12 (these are references to the HagerZhang paper)
- [x] Newton now defaults to BackTracking()
- [x] L-BFGS now defaults to BackTracking()
- [x] BFGS now defaults to BackTracking()

### CODE REVIEW

**Comment by pkofod** [comment]
Just because I'm lazy, `BackTracking()` defaults to the cubic interpolation right?

**Comment by anriseth** [comment]
It defaults to cubic, yes. We should probably do a benchmark in the future
to choose which order (or other linesearch) that's best as default.

**Comment by pkofod** [comment]
> It defaults to cubic, yes. We should probably do a benchmark in the future to choose which order (or other linesearch) that's best as default.

I'm pretty sure I benchmarked backtracking at some point, and cubic was a bit better if I'm not mistaken (on some subset of cutest). Didn't save the results though...

**Comment by pkofod** [comment]
Did you benchmark it since you reverted?

**Comment by anriseth** [comment]
> Did you benchmark it since you reverted?

I ran some benchmarks, and there weren't any clear improvements in terms of the metric used in `OptimTests`. 
It is likely cheaper in terms of gradient evaluations (and potentially f-calls) to use BackTracking, however, we should have some clear rules on evaluating performance before changing defaults I'd say.

**Comment by anriseth** [comment]
This is good to go now, we just need to tag LineSearches.  
It should not be making any breaking changes, or changes to defaults compared to current master.

**Comment by anriseth** [comment]
This is good to go from my side. I propose this PR is merged before the others are, to make rebasing easier.

**Comment by pkofod** [comment]
Is the line searches bump necessary? It's just that we can't just tag a patch if we change require and it should still work with an older version even if you will get warnings right?

**Comment by anriseth** [comment]
The bump is necessary to allow for the alphaguess property in the solvers.
(E.g. alphaguess=InitialStatic()) Or have I misunderstood what you mean?

**Comment by pkofod** [comment]
Alright then it's just my weird local version of optim, thought I was on the latest tag

**Comment by anriseth** [comment]
The current master works with both the newest LineSearches and older versions, but this PR only works with the newest LineSearches :p

**Comment by pkofod** [comment]
Thanks as always!

**Pull request merged**
