### PR TITLE
Don't re-create the cache in every iteration of Fminbox as it calls the objective too often

### PR DESCRIPTION
**Pull request by pkofod**
#704

### CODE REVIEW

**Comment by neoabs** [comment]
I have it to:

image

My code is:
`results = optimize(prices -> objective_function(prices, mdl, method_cube), lower, upper, mdl.Prices , Fminbox(NelderMead() ) )
`
`mdl` is a `mutable struct` `method_cube` is a string. Using standard simplex.

**Comment by pkofod** [comment]
Is that with this branch? That picture looks identical to the other one you posted @neoabs

**Comment by neoabs** [comment]
@pkofod you are correct, I misunderstood you.

 I ll try new branch tomorrow and get back to you.

**Comment by pkofod** [comment]
Oh no worries, I was just confused if you had run it again and gotten the same thing or if this was the same run. They looked identical which makes sense given that they are identical :)

**Comment by pkofod** [comment]
Please report back if you still see issues after the new version is tagged.

**Comment by neoabs** [comment]
`ERROR: LoadError: type BarrierWrapper has no field f_calls
Stacktrace:
 [1] getproperty(::Optim.BarrierWrapper{OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1}},Optim.BoxBarrier{Array{Float64,1},Array{Float64,1}},Float64,Float64,Array{Float64,1}}, ::Symbol) at ./Base.jl:33
 [2] value!!(::Optim.BarrierWrapper{OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1}},Optim.BoxBarrier{Array{Float64,1},Array{Float64,1}},Float64,Float64,Array{Float64,1}}, ::Array{Float64,1}) at /home/szpieg/.julia/packages/NLSolversBase/5oIMo/src/interface.jl:7
 [3] initial_state(::NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters}, ::Optim.Options{Float64,Nothing}, ::Optim.BarrierWrapper{OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1}},Optim.BoxBarrier{Array{Float64,1},Array{Float64,1}},Float64,Float64,Array{Float64,1}}, ::Array{Float64,1}) at /home/szpieg/.julia/packages/Optim/KE5Mt/src/multivariate/solvers/zeroth_order/nelder_mead.jl:158
 [4] optimize(::OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Fminbox{NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters},Float64,Optim.var"#45#47"}, ::Optim.Options{Float64,Nothing}) at /home/szpieg/.julia/packages/Optim/KE5Mt/src/multivariate/solvers/constrained/fminbox.jl:307
 [5] optimize(::Function, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Fminbox{NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters},Float64,Optim.var"#45#47"}, ::Optim.Options{Float64,Nothing}; inplace::Bool, autodiff::Symbol) at /home/szpieg/.julia/packages/Optim/KE5Mt/src/multivariate/solvers/constrained/fminbox.jl:254
 [6] optimize(::Function, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Fminbox{NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters},Float64,Optim.var"#45#47"}, ::Optim.Options{Float64,Nothing}) at /home/szpieg/.julia/packages/Optim/KE5Mt/src/multivariate/solvers/constrained/fminbox.jl:253 (repeats 2 times)
 [7] hans_solver(::ModelInit{Float64}, ::Array{Float64,1}, ::Array{Float64,1}; method_cube::String) at /home/szpieg/Julia/grant/HANS/HANS_solver/solver/solver.base.jl:7
 [8] hans_solver(::ModelInit{Float64}, ::Array{Float64,1}, ::Array{Float64,1}) at /home/szpieg/Julia/grant/HANS/HANS_solver/solver/solver.base.jl:5 (repeats 2 times)
 [9] top-level scope at /home/szpieg/Julia/grant/HANS/HANS_solver/mymodel.jl:19
in expression starting at /home/szpieg/Julia/grant/HANS/HANS_solver/mymodel.jl:19`

same code as above. I updated packages prior to that. Am I doing something wrong or is there some other issue?

**Pull request merged**
