### PR TITLE
Add usage example to complex optimization

### PR DESCRIPTION
**Pull request by anriseth**
We should probably find a clever way to add Literate examples to the Examples section of existing docs. Alternatively, we could just list links to them in the `complex.md` file.

Also, @antoine-levitt, do you have any references for me that can be useful to add to the docs?

### CODE REVIEW

**Comment by pkofod** [comment]
> We should probably find a clever way to add Literate examples to the Examples section

This is something for you to consider @iewaij

**Comment by iewaij** [comment]
Yeah I can work on it!

**Comment by antoine-levitt** [comment]
Really the definition should be enough. There's https://arxiv.org/pdf/0906.4835.pdf which is very verbose but covers the material.

**Comment by anriseth** [comment]
Good to go :+1:

**Pull request merged**
