### PR TITLE
Fix project_tangent! and retract! args in manual

### PR DESCRIPTION
**Pull request by thisrod**

### CODE REVIEW

**Comment by antoine-levitt** [comment]
Looks good, thanks!

**Comment by thisrod** [comment]
I've been playing with the manifold of wave functions whose vortices are pinned at fixed positions, but whose density and phase can otherwise relax.  When it's a bit more stable, I'll write it up as an example.

**Comment by antoine-levitt** [comment]
Ah nice I'd be interested in knowing more

**Comment by pkofod** [comment]
Oh, good catch. Thanks! And yes, we're always happy to hear about usecases and user-written manifolds!

**Comment by antoine-levitt** [comment]
I've been meaning to interface with https://github.com/JuliaManifolds/Manifolds.jl/ for a while, but never got around to it

**Pull request merged**
