### PR TITLE
Use OptimTestProblems

### PR DESCRIPTION
**Pull request by anriseth**
This uses OptimTestProblems for testing.

Some notes:
- I haven't thoroughly checked why solvers don't converge on problems, so we should go through that on all the `skip` and `*_exceptions` problems in `run_optim_problems`
- None of the solvers deals with "Trigonometric", as they all converge to a local minimum
- In `run_optim_problems`, I now allow the TwiceDifferentiable solvers to run the problems that only provide gradients via finite differencing

Fixes https://github.com/JuliaNLSolvers/OptimTestProblems.jl/issues/3

### CODE REVIEW

**Comment by anriseth** [comment]
We need https://github.com/JuliaLang/METADATA.jl/pull/12865 for tests to work.

**Comment by pkofod** [comment]
Wonderful, will be good to have these out of Optim!

**Comment by ChrisRackauckas** [comment]
Re-run

**Comment by pkofod** [comment]
momentum is acting up

**Comment by anriseth** [comment]
(L-)BFGS failed due to `f_increase`. Windows is behaving differently, so @pkofod how would you like to deal with that? Should we just skip all problems that fail on Windows (but not Linux) for now?

**Comment by pkofod** [comment]
Yes that is fine

**Comment by anriseth** [comment]
Ready to merge. The Travis MacOS queue has a many-hour long backlog, so we should probably wait and see that things pass there as well.

**Comment by ChrisRackauckas** [comment]
Travis Mac is just down. I wouldn't wait.

**Comment by anriseth** [comment]
Mac didn't fail us :champagne:

**Comment by pkofod** [comment]
Great stuff

**Pull request merged**
