### PR TITLE
Short explanation of the Rosenbrock function.

### PR DESCRIPTION
**Pull request by Wikunia**
There might be some people out there who are not familiar with the Rosenbrock function but are interested in this package ;)

### CODE REVIEW

**Comment by pkofod** [comment]
Thanks for noticing our package, and thanks for this improvement of our readme! Hope you enjoyed using Optim so far. 

Yes it's a good idea to reference what we're doing, and show in math what the objective is. Sometimes I and others are so used to looking at the code and readme, that we don't really see that things like this can be helpful.

May I suggest you change the img-link to point to the image below?

formula

This way, the image should be accessible as long as github is. I'm not saying codecogs isn't going to stay accessible, but you never know!

**Comment by Wikunia** [comment]
I just started to learn Julia and just creep around some packages and Optim seems quite interesting. 
Don't have a project for it atm but maybe try some stuff using it. Anyway thanks for the package. It looks nice :)

**Comment by pkofod** [comment]
If it's hard to find out how to do something, the docs are probably lacking (and they are). If so, we do appreciate PRs :wink:

**Comment by pkofod** [comment]
Thanks!

**Pull request merged**
