### PR TITLE
First stab at maximize convenience functionality

### PR DESCRIPTION
**Pull request by pkofod**
```
julia> using Optim

julia> f(x) = -x[1]^2-2*x[2]^2
f (generic function with 1 method)

julia> Optim.maximize(f, x0, Newton(), Optim.Options())
Results of Optimization Algorithm
 * Algorithm: Newton's Method
 * Starting Point: [0.37864232579886337,0.5962180744702512]
 * Maximizer: [-2.4734658765623863e-12,1.5709655798445965e-12, ...]
 * Maximum: -1.105390e-23
 * Iterations: 1
 * Convergence: true
   * |x - x'| ≤ 0.0e+00: false
     |x - x'| = 5.96e-01
   * |f(x) - f(x')| ≤ 0.0e+00 |f(x)|: false
     |f(x) - f(x')| = 7.73e+22 |f(x)|
   * |g(x)| ≤ 1.0e-08: true
     |g(x)| = 4.95e-12
   * Stopped by an decreasing objective: false
   * Reached Maximum Number of Iterations: false
 * Objective Calls: 4
 * Gradient Calls: 4
 * Hessian Calls: 1
```

- [x] cover all of api, not just the stuff used in `show`
- [ ] convert `NDifferentiable`'s to negated versions if they're passed (I guess `deepcopy` and then change fields)
- [ ] handle `allow_f_increases` -> `allow_f_decreases`
- [ ] ...
- [ ] profit?

### CODE REVIEW

**Comment by pkofod** [comment]
ref #554 #308

**Comment by jlperla** [comment]
Looks good to me. As a reminder for @arnavs make sure to test the permutations of numerical vs analytical gradients, hessians, or whatever for inplace, out of place, etc. since there are so many different ways to have functions called. I think that the test functions, however, can be kept very simple (eg quadratic, etc making sure there is a minimum) so analytical derivatives are a joke for those that tests

**Comment by arnavs** [comment]
@pkofod OK, I have put some docs and tests in my fork (@arnavs/Optim.jl). The tests are the univariate case (`cos`), and some basic multivariates like Jesse suggested (negative paraboloid, and negative Rosenbrock). 

I think there is an issue in getting this to run that is above my paygrade. In particular, the `invalid redefinition of constant method` that's thrown [here](https://github.com/JuliaNLSolvers/Optim.jl/pull/654/files#diff-820c225a803f9d6216a45afef937e686R30). See the [Travis build](https://travis-ci.org/arnavs/Optim.jl/jobs/413725475) for specifics.

**Comment by jlperla** [comment]
@pkofod  I discussed this with @arnavs , and the basic story is that your PR breaks the building prior to any tests, as soon as it is added to the repo.  He can explain better, but I think that is the key (i.e., not that a particular test is failing,... more that you can't get to any of them).

**Comment by arnavs** [comment]
Thanks Jesse for explaining. That's basically the story; when I add that file to the package and then export the objects (`maximize, maximizer, MaxWrap`), there is that issue which fails before any tests are run.

**Comment by pkofod** [comment]
Oh, I realize that in the PR I forgot to `add src/Optim.jl` (did you do that in your branch?)

**Comment by arnavs** [comment]
Yeah. The issue is that once you `include("src/.../maximize.jl)`, the thing breaks, I think because of the actions we're performing on these methods.

**Comment by pkofod** [comment]
Ill fix it :)

**Comment by arnavs** [comment]
Will answer on Slack.

**Pull request merged**
