### PR TITLE
Fixes 2/3 of problems with Nelder Mead related traces

### PR DESCRIPTION
**Pull request by eirikbrandsaas**
Fixes the first two the issues raised in #941 

I tried to fix the last one, but that was beyond my capabilities. If you give me a pointer I should be able to figure it out.

### CODE REVIEW

**Comment by pkofod** [comment]
Thanks for looking into this. It looks fine. I would appreciate if you could add a test for the missing `tr` thing, just to make sure that the code path is run as part of the tests.

**Comment by eirikbrandsaas** [comment]
Sure, at least if you can slightly more specific on what you want. You just want me write a test that simply checks that the command works? In which of the many `test/` files should it go?

**Comment by pkofod** [comment]
> Sure, at least if you can slightly more specific on what you want. You just want me write a test that simply checks that the command works? In which of the many `test/` files should it go?

Yes, just checking that what you changed does what you intended.  Here would be a good place https://github.com/JuliaNLSolvers/Optim.jl/blob/master/test/multivariate/solvers/zeroth_order/nelder_mead.jl. Just add a testset with title `#942`

**Comment by eirikbrandsaas** [comment]
Okay, I'll get it done sometime "soon".

**Comment by eirikbrandsaas** [comment]
"Soon" became 6 months, but hey, who is counting?

I see now that you wanted me to post a separate pull request, but hope this works.

Note that, as mentioned in #941 that the stored trace is wrong, it replaces all simplex values with the last one. (That's why there are two `@test_broken` in the pull request. 

Too see this:
```julia
using Optim
f(x) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
x0 = [0.0,0.0]
res = optimize(f, x0, NelderMead(),Optim.Options(store_trace=true,trace_simplex=true,extended_trace=true,iterations=2,show_trace=true))
display(res.trace)
```
and compare the output of the simplexes (both y-values and x-simplexes) from the "running" trace and the stored res.trace.

**Comment by eirikbrandsaas** [comment]
@pkofod Just pinging. 

(See comment above)

**Pull request closed without merging**
