### PR TITLE
[WIP] adding Natural Evolution Strategies

### PR DESCRIPTION
**Pull request by francescoalemanno**
https://github.com/JuliaNLSolvers/Optim.jl/issues/804

things to do:
* <strike>integrate Separable NES </strike>[done]
* <strike>integrate Exponential NES </strike>[done]
* improve integration: tracing and options
* better testing
* further performance improvements?

### CODE REVIEW

**Comment by francescoalemanno** [comment]
RFC

**Comment by pkofod** [comment]
Quick question: are these straight from the paper you linked in the issue? I appreciate a hard reference in the source code for easy reference. Also, I'd appreciate some comments in the code. But I'll have a look. Thanks

**Comment by francescoalemanno** [comment]
no longer got time to work on this

**Comment by pkofod** [comment]
You didn't have to close the PR though, others could have finished it :) Can you answer my question by any chance? Were these implementations based 1-to-1 on the paper you posted?

**Comment by francescoalemanno** [comment]
Sorry i didn't know that closing, stops others from working on my code... i just got started with the PR mechanism and github, anyway i decided to mantain an independent implementation of Nes's

the implementation in the commits here is almost a 1-1 clone of http://www.jmlr.org/papers/volume15/wierstra14a/wierstra14a.pdf

the only difference is in separable NES, where i keep the most promising directions (resampling their magnitude according to gaussian statistics) in order to speed it up considerably.

if anyone is interested in continuing this work, they are free to copy paste from the commit listing.

if i knew the consequence of closing would be this inconvenience i would have avoided it, sorry again!

**Comment by pkofod** [comment]
No worries! Thanks for the clarifying comments :)

**Pull request closed without merging**
