### PR TITLE
RMSprop

### PR DESCRIPTION
**Pull request by krzysztofdabkowski1**
New multivariate solver based on GradientDescent and RMSprop algorithm

### CODE REVIEW

**Comment by pkofod** [comment]
Thanks for the PR. I will have a look. I was actually just reading the steps to do Adam last night prompted by 

Is it really standard to perform a line search step?

**Comment by krzysztofdabkowski1** [comment]
Nominally, RMSprop doesn't use line search, but I think it's not efficient (compared to accelerated variants of Gradient Descent). This method is combined of traditional Gradient Descent with line search and element calculated from RMSprop algorithm, which accelerate each iteration.

**Comment by pkofod** [comment]
> but I think it's not efficient (compared to accelerated variants of Gradient Descent)

On what kinds of problems? RMSprop is meant for mini batches right? Are you sure this is good in the context of "stochastic" objectives as well?

**Comment by krzysztofdabkowski1** [comment]
OK, probably you're right. I will correct it and write in traditional way.

**Comment by pkofod** [comment]
> OK, probably you're right. I will correct it and write in traditional way.

I should say that the other accelerated methods (that are largely here for historical reasons) also default to a line search, but I don't think they should necessarily either.

**Comment by krzysztofdabkowski1** [comment]
> I should say that the other accelerated methods (that are largely here for historical reasons) also default to a line search, but I don't think they should necessarily either.

So, you think that implementing it even with default to static doesn't make sense. Am I right?

**Comment by pkofod** [comment]
> So, you think that implementing it even with default to static doesn't make sense. Am I right?

I think it would make sense to chose `Static()` as the standard.

**Pull request closed without merging**
