### PR TITLE
Use dot notation

### PR DESCRIPTION
**Pull request by anriseth**
Newton is being fixed in #474

### CODE REVIEW

**Comment by pkofod** [comment]
:+1: let's merge when travis finishes

**Comment by anriseth** [comment]
I updated this because @pkofod did the same in #474 for Newton. I'm not sure how the axpy functionality works, but could it be that dot-notation can support a wider range of types?

**Comment by pkofod** [comment]
> Out of curiosity: why was this changed?

Well, I think dots read a bit cleaner than level-1 blas calls. Do you think it matters for something? (performance, genericity, ...)

**Comment by fredrikekre** [comment]
`state.alpha * state.s` will allocate a new vector. Should have been `state.alpha .* state.s` (?)

**Comment by pkofod** [comment]
Yes, that should have been dotted as well.

**Pull request merged**
