### PR TITLE
Actually stop at line search failure

### PR DESCRIPTION
**Pull request by gwater**
addresses #789

### CODE REVIEW

**Comment by gwater** [comment]
I dont understand why Windows x64 breaks and everything else works.

**Comment by pkofod** [comment]
Thanks!

Yeah, some times there can be subtle differences between Linux and Windows. I will try to see if I can figure out what is going on.

**Comment by gwater** [comment]
I think we can deduce nevertheless that the differencent behavior between Windows x64 and other operating systems are not due to this change. Therefore I think it should be adressed in a separate issue / PR

**Comment by gwater** [comment]
The failing test is FMinBox using Nonlinear GMRES preconditioned with Gradient Descent

**Comment by pkofod** [comment]
It's fine to remove that specific run then.

**Comment by gwater** [comment]
ok, I'll make a patch to mark it as broken on Windows x64

**Comment by gwater** [comment]
done

**Comment by pkofod** [comment]
Thanks a lot, this was a very stupid oversight on my part.

**Pull request merged**
