### PR TITLE
Add tests for f,g,h counters

### PR DESCRIPTION
**Pull request by anriseth**
Requires #411

### CODE REVIEW

**Comment by pkofod** [comment]
This should probably change LineSearches require to 2.1.0

**Comment by anriseth** [comment]
I've bumped the version. 
Tests will fail until https://github.com/JuliaNLSolvers/NLSolversBase.jl/pull/10 is merged. So until then, we could either wait with this PR, or I can "fix" the tests by adding extra counts

**Comment by pkofod** [comment]
Could you do a version that works now, with the "future" versions commented out?

**Comment by pkofod** [comment]
Ready?

**Pull request merged**
