### PR TITLE
WIP: CG/Krylov Trust Region method

### LINKED ISSUE #356: Hessian-vector products
Have you all considered adding optimization methods that make use of Hessian-vector products, but that don't explicitly form Hessians? I've been thinking about writing a version of `newton_trust_region` that does that, essentially using conjugate gradient iterations to multiply the gradient by the inverse Hessian. Is that something you'd be interested in including in Optim.jl?

jeff-regier/Celeste.jl#380

### PR DESCRIPTION
**Pull request by jeff-regier**
@pkofod  Here's a PR for a trust region method that uses Hessian-vector products. I thought I'd post it now since I'm not sure how you want Optim's types to handle functions that are twice differentiable but only support Hessian-vector products. In the PR, I added a new function type `TwiceDifferentiableHV` but I thought you might be able to suggest a better way.

Also, please let me know what other changes and additions to make to get the PR merged.

Once complete, this PR closes #356.

### CODE REVIEW

**Comment by KristofferC** [comment]
I think everything written as e.g. `z[:] += tau * d` could be written with the fusing dot syntax as `z .+= tau .* d`. This should avoid forming any temporaries and work totally in place.

**Comment by pkofod** [comment]
> @pkofod Here's a PR for a trust region method that uses Hessian-vector products. I thought I'd post it now since I'm not sure how you want Optim's types to handle functions that are twice differentiable but only support Hessian-vector products. In the PR, I added a new function type TwiceDifferentiableHV but I thought you might be able to suggest a better way.

I'll have a look! Great to see you getting around to this. Have you played around with it in Celeste?

**Comment by pkofod** [comment]
You may not have noticed, but we moved the `*Differentiable`-stuff to https://github.com/JuliaNLSolvers/NLSolversBase.jl so that is where `TwiceDifferentiableHV` should go. I'm not sure I can think of a better solution than yours off the top of my head... I like that you placed all methods in the same file. We should really move all the trace code for the other solvers to their respective files as well.

**Comment by jeff-regier** [comment]
It's running on Celeste's `jcr/cg2` branch now, with Hessian-vector products computed by ForwardDiff.jl. It works well at getting the right result. It can take a lot of Hessian-vector products though, for our application. I'm working on ways of making it more efficient. (The implementation in this PR is pretty much textbook N&W.) There's an extension to the N&W approach that uses Lanczos iterations as well as CG iterations that I'm exploring.

**Comment by jeff-regier** [comment]
What about adding an `hv!` field to `TwiceDifferentiable` in NLSolversBase, that gets populated in the constructor automatically if the caller specifies `h!` but not `hv!`? And if a constructor is called with `hv!` but not `h!`, then `h!` is set to a function that throws a "not implemented" exception if called?

That way there's just one `TwiceDifferentiable` type, differentiability is really a property of the underlying function, not the ways of observing the function.

An alternative might be to do something with type parameters, to avoid any possibility of the `h!` method throwing an exception, but I'm not exactly sure how that would work.

**Comment by pkofod** [comment]
> What about adding an hv! field to TwiceDifferentiable in NLSolversBase, that gets populated in the constructor automatically if the caller specifies h! but not hv!? And if a constructor is called with hv! but not h!, then h! is set to a function that throws a "not implemented" exception if called?
> 
> That way there's just one TwiceDifferentiable type, differentiability is really a property of the underlying function, not the ways of observing the function.
> 
> An alternative might be to do something with type parameters, to avoid any possibility of the h! method throwing an exception, but I'm not exactly sure how that would work.

Had not seen your response. Do you mean something like keeping fields for `h!` and `hv!` and then use a keyword to specify which one it is? 
```julia
...
hv! = ...
td = TwiceDifferentiable(..., hv!, ; hessianvector = true)
```
?

**Comment by jeff-regier** [comment]
Yes, that sounds like a good way to do it. I hadn't thought through whether we'd use a keyword argument like `hessianvector = true`, but I suppose that makes sense.

**Comment by pkofod** [comment]
> Yes, that sounds like a good way to do it. I hadn't thought through whether we'd use a keyword argument like hessianvector = true, but I suppose that makes sense.

Just to understand your earlier comment correctly, you would say that this works but didn't prove to be particularly fast compared to your existing approach in Celeste, or?

**Comment by jeff-regier** [comment]
Yes, that's the case. For Celeste we're only optimizing 44 parameters at once so forming a dense hessian isn't all that slow. We'll nonetheless probably switch to using a krylov method eventually because it's so tedious to modify any code that computes the Hessian.

**Comment by pkofod** [comment]
Alright, I take it you are fine that we wait with the merge until we converge on the best way to specify that hessian-vector products are to be used. In the mean time, I'll try to find some good test cases with large hessians

**Comment by jeff-regier** [comment]
Yes, no rush for me, I can wait until hessian-vector products are in NLSolversBase. @rgiordan wanted to use this code eventually for his work, but I'm not sure how soon he needs it.

**Comment by rgiordan** [comment]
Yes, if I'm going to use Julia for my research projects I'll need something that does second-order optimization using Hessian-vector products.  If this isn't checked in I can look into either trying to maintain a  version myself for private use or use port from C or Python.

**Comment by anriseth** [comment]
> In the mean time, I'll try to find some good test cases with large hessians

> Yes, if I'm going to use Julia for my research projects I'll need something that does second-order optimization using Hessian-vector products. 

Sounds to me like @rgiordan may have some test cases for you @pkofod ?

**Comment by rgiordan** [comment]
I do have use cases!  When you're doing perturbation analysis on an optimization problem with a large number of latent variables (e.g. large GLMMs fit with variational inference), you need to be at a high-quality optimum in terms of the gradient being very close to zero and the Hessian actually being positive definite.  I've found that it's necessary to use actual second-order optimization to get there -- quasi-second order methods like BFGS doesn't do a good job.  And if you have a lot of latent variables, calculating the exact Hessian can be prohibitive, at least with autodiff.

I have a paper draft for motivation and python code to share, but since it's still unpublished I'd rather share it privately.  @pkofod , if you're interested, please email me (rgiordano@berkeley.edu).

**Comment by pkofod** [comment]
Just had a talk with @rgiordan , and as I told him, I basically think we might as well just merge this as is, and then we can try the design out before moving anything to a base package that affects other packages than Optim.

There are some changes I want to do here to make it up-to-date with other stuff in Optim, but I can do that myself after a merge. What's most important, I think, is to have a working implementation that we can play around with. We'll just list it as experimental, or just not list it at all ;)

**Comment by jeff-regier** [comment]
There isn't a lot left to do---just rebasing, enabling the unit tests (the were running locally but now they are commented out because of breaking changes), and adding some basic documentation. But unfortunately I don't think I'm going to have time to work on it during the next couple of months. I will get to it then. Or I'm glad for someone else to take over this PR.

**Comment by pkofod** [comment]
> I will get to it then. Or I'm glad for someone else to take over this PR.

I will see if I can find the time, would you maybe have time to answer a few basic questions if necessary?

**Comment by jeff-regier** [comment]
Yes, glad to answer any questions. Thanks for any help getting this merged.

**Comment by rgiordan** [comment]
Awesome, thanks everyone!  I'll give it a spin.

**Comment by jeff-regier** [comment]
Thanks for seeing it through @pkofod !

**Pull request merged**
