### PR TITLE
Bump FillArrays version bound

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by magerton** [comment]
Getting this merged would be great -- currently Optim & BoundaryValueDiffEq are imposing unresolvable package conflicts w/ FillArrays...

**Comment by pkofod** [comment]
> Getting this merged would be great -- currently Optim & BoundaryValueDiffEq are imposing unresolvable package conflicts w/ FillArrays...

Sure, but this was posted 19 hours ago, and I've not been at a computer.

**Comment by magerton** [comment]
Of course, @pkofod -- I didn't mean to come across as pushy. There's a lot to do managing all the PRs, and I appreciate all the work you do to maintain Optim.jl!

**Comment by pkofod** [comment]
No worries, auto tag bot makes things fast :)

**Pull request merged**
