### PR TITLE
Use abstract type instead of typealias for solver distinction.

### PR DESCRIPTION
**Pull request by pkofod**
@anriseth @jonathanBieler

Are there other things you found annoying while trying to base your stuff off of Optim? I'll be happy to generalize where needed.

### CODE REVIEW

**Comment by anriseth** [comment]
Thanks :)

One thing that can be convenient to access from outside of Optim is multiple dispatch on functions such as `default_convergence_assessment`: https://github.com/JuliaNLSolvers/Optim.jl/blob/d55a8a443abed8cbca2a0b8aa38fe2bc148bf8ac/src/utilities/assess_convergence.jl#L47 
and (this one is my fault :p ) https://github.com/JuliaNLSolvers/Optim.jl/blob/d55a8a443abed8cbca2a0b8aa38fe2bc148bf8ac/src/multivariate/solvers/zeroth_order/zeroth_utils.jl#L1

**Comment by pkofod** [comment]
I'll fix the 0th order states and the default convergence. Maybe I should try to implement something outside of Optim again (or update constrainedoptim.jl) to get a feel myself.

**Comment by anriseth** [comment]
There might be something connected with default tracing functions as well,
however, new algorithms probably have special info that they should be
providing via trace.

**Comment by pkofod** [comment]
> There might be something connected with default tracing functions as well,
> however, new algorithms probably have special info that they should be
> providing via trace.

Yes I think they'll probably by "special" in some way, with some specific things to add to the extended trace. I do think that our trace/convergence/options stuff is far too hardcoded but we can fix that at a later stage.

**Comment by pkofod** [comment]
@anriseth @jonathanBieler I hope this removes some of the annoyances. I will tag a new version soon.

**Comment by jonathanBieler** [comment]
Thanks, I'll try this in a few days.

**Pull request merged**
