### PR TITLE
Fix only_fgh! support

### LINKED ISSUE #664: only_fgh! not working
```julia
f(x) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
function g!(G, x)
  G[1] = -2.0 * (1.0 - x[1]) - 400.0 * (x[2] - x[1]^2) * x[1]
  G[2] = 200.0 * (x[2] - x[1]^2)
end
function h!(H, x)
  H[1, 1] = 2.0 - 400.0 * x[2] + 1200.0 * x[1]^2
  H[1, 2] = -400.0 * x[1]
  H[2, 1] = -400.0 * x[1]
  H[2, 2] = 200.0
end
function fg!(F,G,x)
  G == nothing || g!(G,x)
  F == nothing || return f(x)
  nothing
end
function fgh!(F,G,H,x)
  G == nothing || g!(G,x)
  H == nothing || h!(H,x)
  F == nothing || return f(x)
  nothing
end

import Optim
Optim.optimize(Optim.only_fg!(fg!), [0., 0.], Optim.LBFGS()) # works fine
Optim.optimize(Optim.only_fgh!(fgh!), [0., 0.], Optim.Newton()) 
# ERROR: MethodError: objects of type NLSolversBase.InplaceObjective{Nothing,Nothing,typeof(fgh!)} are not callable
```

See also https://discourse.julialang.org/t/optim-jl-computing-value-gradient-and-hessian-simultaneously/1219/15.

### PR DESCRIPTION
**Pull request by pkofod**
Fix  #664

### CODE REVIEW

**Comment by cossio** [comment]
Thanks for this. Maybe add a test? Something like this:

```julia
f(x) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
function g!(G, x)
  G[1] = -2.0 * (1.0 - x[1]) - 400.0 * (x[2] - x[1]^2) * x[1]
  G[2] = 200.0 * (x[2] - x[1]^2)
end
function h!(H, x)
  H[1, 1] = 2.0 - 400.0 * x[2] + 1200.0 * x[1]^2
  H[1, 2] = -400.0 * x[1]
  H[2, 1] = -400.0 * x[1]
  H[2, 2] = 200.0
end
function fg!(F,G,x)
  G == nothing || g!(G,x)
  F == nothing || return f(x)
  nothing
end
function fgh!(F,G,H,x)
  G == nothing || g!(G,x)
  H == nothing || h!(H,x)
  F == nothing || return f(x)
  nothing
end

import Optim
#Optim.optimize(Optim.only_fg!(fg!), [0., 0.], Optim.LBFGS()) # works fine
Optim.optimize(Optim.only_fgh!(fgh!), [0., 0.], Optim.Newton()) 
```

**Comment by pkofod** [comment]
> Thanks for this. Maybe add a test? Something like this:

Yes! It was just kind of late here, and I wanted to push this so I didn't forget :) We should also have better documentation and perhaps also slightly improve the code so it actually takes advantage of this better in `Newton()`.

**Comment by pkofod** [comment]
Looks like most changes were to docs since last change https://github.com/JuliaNLSolvers/Optim.jl/compare/v0.17.2...master so yes, I can tag "soon". I'll go through the recent commits tonight and tag a version of nothing requires deprecations or similar.

**Comment by cossio** [comment]
Ah, deprecations... Okay if its too complicated nevermind, I'll just `add Optim#master`.

**Pull request merged**
