### PR TITLE
Add option for disabling warnings

### PR DESCRIPTION
**Pull request by MilesCranmer**
This my second attempt at https://github.com/JuliaNLSolvers/Optim.jl/pull/1049. This time I add a new option for configuring this. 

@mohamed82008 @pkofod could you please prioritize reviewing and merging one of these? For the past 3 months this has been blocking us from upgrading our ecosystem of symbolic regression tools to the latest version of Optim.jl.

I have kept #1049 open FYI. I'm happy with either one, I just need a way to turn the warnings off, lest PySR's output be overrun with unnecessary warnings.

### CODE REVIEW

**Comment by MilesCranmer** [comment]
Ping @mohamed82008 @pkofod. Sorry for being annoying but I've been waiting for this since August and it is still blocking me from upgrading.

**Comment by pkofod** [comment]
> Ping @mohamed82008 @pkofod. Sorry for being annoying but I've been waiting for this since August and it is still blocking me from upgrading.

not annoying. Your ping to Mohamed managed to make its way through him to me :) I'll look. Thanks

**Comment by MilesCranmer** [comment]
Thanks again for merging this @pkofod!

I was wondering if you or @mohamed82008 might be able to trigger a release so I can update my dependencies?

**Comment by pkofod** [comment]
I'll tag a new release, yes

**Pull request merged**
