### PR TITLE
Use docs/Project.toml for building docs.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by pkofod** [comment]
Thanks! Glad to see this being handled outside of `runtests`.

**Comment by fredrikekre** [comment]
Yea, using Travis build stages like this is pretty nice, it will still fail the build, which was the reason to have doc building in `runtests.jl` in the first place.

**Comment by Evizero** [comment]
this is cool

**Comment by pkofod** [comment]
> Yea, using Travis build stages like this is pretty nice, it will still fail the build, which was the reason to have doc building in `runtests.jl` in the first place.

Very happy to have an expert drop by! :)

**Comment by fredrikekre** [comment]
64-bit failures on AV seems unrelated.

**Pull request merged**
